image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache curl bash git openjdk17 maven

build:
  stage: build
  script:
    - mvn clean package -Dmaven.test.skip=true
    - docker build -t myapp:latest .

