stages:
  - build
  - test
  - deploy

# build 階段：負責打包
build:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

# test 階段：負責執行單元測試
test:
  stage: test
  image: maven:3.8.5-openjdk-17
  script:
    - mvn test

# deploy 階段：用 docker build & run 執行應用
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-app-image:latest .
    - docker run --rm my-app-image:latest
