spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/BillDB
    driver-class-name: org.postgresql.Driver
    username: Bill
    password: bill21250025

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false